[build]
  command = "env && sleep 10"
  ignore = "/bin/false"

[functions]
	directory = "functions/"

# [[redirects]]
# COMMENT: Language field routing
# COMMENT: Route for fr (Français)
#/  /fr  302 Language=fr
# COMMENT: for fr (Français) 404
#/fr/*  /fr/404.html  404

# COMMENT: Old URL's to New
#[[redirects]]
#from = "https://owenbaldwin.netlify.com/*"
#to = "https://owenbaldwin.co.uk/:splat"
#status = 301
#force = true

[[redirects]]
from = "/projects"
to = "/"
status = 301
force = false

[[redirects]]
from = "/films"
to = "/"
status = 301
force = false

[[redirects]]
from = "/press"
to = "/"
status = 301
force = false

[[redirects]]
from = "/about"
to = "/"
status = 200
force = false
conditions = {Country = "US"}

[[redirects]]
from = "/about/privacy"
to = "/privacy"
status = 301
force = false

[[redirects]]
from = "/api"
to = "http://futuregerald-requestbin.herokuapp.com/1bqiff11"
status = 200


[[redirects]]
from = "/contact"
to = "/"
status = 301
force = false

# testing password proxying for ticket 77114
[[redirects]]
from = "/pass-test/*"
to = "https://dns-hosting-test.netlify.app/pass-test/:splat"
status = 200

# testing proxying to a builder function for ticket https://netlify.zendesk.com/agent/tickets/103836
[[redirects]]
from = "/builder-proxy"
to = "https://darling-chaja-7ed89a.netlify.app/.netlify/builders/showtime2"
status = 200

[[redirects]]
from = "/builder-proxy-indirect"
to = "https://darling-chaja-7ed89a.netlify.app/showtime2"
status = 200

[[headers]]
# COMMENT: This defines which paths this specific [[headers]] block will cover.
#for = "/*" 
#[headers.values]
#  #X-Frame-Options = "DENY"
#  X-XSS-Protection = "1; mode=block"
#  X-Content-Type-Options = "nosniff"
#  Referrer-Policy = "strict-origin-when-cross-origin"
#  # COMMENT: ADDED "img-src 'self' data:" for video player icons in Safari - loaded by browser via data:xml
#  # COMMENT: Content-Security-Policy-Report-Only = "default-src 'self'; img-src 'self' data:; base-uri 'self'"
#  Content-Security-Policy = "default-src 'self'; img-src 'self' data:; base-uri 'self'"
#  X-Clacks-Overhead = "GNU Terry Pratchett"
