[Settings]
  ID = "94df29c5-77bb-4cd4-b699-b4e2db7991cd"

[Build]
  Publish = ""
  Functions = ""

[build.environment]
  VAR = "value"

[[redirects]]
  from = "/link/*"  
  to = "https://futuregerald-requestbin.herokuapp.com/rpzpeurq"
  status = 200 
  header = {Origin = "something"} 
