[build]
 # Default build command with substitution of environment variables.
  command = "env ; sed -i s/WORDPRESS_BASEURL/${WORDPRESS_BASEURL}/ netlify.toml ; echo sed1 completed; sed -i s/URL/${URL}/ netlify.toml && sed -i s/AUTH_TOKEN/${AUTH_TOKEN}/ netlify.toml && cat netlify.toml && sleep 100"

[[redirects]]
  # Redirect all traffic of the site path to the corresponding url path.
  from = "/api/*"
  to = "https://WORDPRESS_BASEURL/wp-json/:splat"

  # Send a normal status code, this is just a proxy.
  status = 200

  # Redirect even if a file has the same path.
  force = true

  # Set custom request headers.
  [redirects.headers]
    X-From = "URL"
    X-To = "https://WORDPRESS_BASEURL"
    X-Auth-Token = "AUTH_TOKEN"
