[Settings]
  ID = "94df29c5-77bb-4cd4-b699-b4e2db7991cd"
  Path = ""

[[redirects]] 
  origin = "/parse"
  destination = "https://requestb.in/1nagh6m1"
  status = 200
  headers = {Host = "kathleen-booth-website.com", X-From = "netlify"}


[build]
  command = "ls -l"
