[Settings]
  ID = "94df29c5-77bb-4cd4-b699-b4e2db7991cd"

[Build]
  Publish = ""
  Functions = ""

[build.environment]
  VAR = "value"

[[redirects]]
  from = "/redirect/*"  
  to = "/bob/:splat?a=:a" 
  status = 302 
  query = {a = ":a"} 
