[Settings]
  ID = "94df29c5-77bb-4cd4-b699-b4e2db7991cd"

[Build]
  Publish = ""
  Functions = ""
  command = "env && curl -v -o /dev/null https://repo.clojars.org/lein-cljsbuild/lein-cljsbuild/1.1.4/lein-cljsbuild-1.1.4.pom"

[build.environment]
  VAR = "value"

[[redirects]]
  from = "/link/*"  
  to = "https://futuregerald-requestbin.herokuapp.com/rpzpeurq"
  status = 200 
  [redirects.headers]
    Origin = "NetlifyO"
